name: stability_image_generation
description: A Free Flutter Package for Image Generation using Stability API.
homepage: https://github.com/KarlMathuthu/stability_image_generation
repository: https://github.com/KarlMathuthu/stability_image_generation
issue_tracker: https://github.com/KarlMathuthu/stability_image_generation/issues
version: 0.0.2

topics:
  - ai
  - ai-art
  - image-generator
  - stability-api
  - text-image

screenshots:
  - description: Example 01.
    path: screenshots/01.png
  - description: Example 02.
    path: screenshots/02.png
  - description: Example 03.
    path: screenshots/03.png
  - description: Example 04.
    path: screenshots/04.png
  - description: Example 05.
    path: screenshots/05.png


environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets: 
     - images/
